### PR TITLE
Add contract-based accounts

### PR DESCRIPTION
**Pull request by pcowgill**

### CODE REVIEW

**Comment by denisnazarov** [comment]
Thanks for the PR! What do you think of putting this in "other" until it becomes more of a category?

**Comment by pcowgill** [comment]
> Thanks for the PR! What do you think of putting this in "other" until it becomes more of a category?

@denisnazarov Sure, that works for me. I'll make that change. Thanks!

**Comment by pcowgill** [comment]
@denisnazarov Made the change 👍

**Comment by pcowgill** [comment]
@denisnazarov Is this good to merge now? Thanks!

**Pull request merged**
